name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to the latest version
      with:
        node-version: '18'  # Using Node.js 18

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
